apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: github-secret
spec:
  path: secret/ad/accel-webapp/gh-secret
  type: kubernetes.io/dockerconfigjson
  keys:
    - username
    - password
  templates:
    ".dockerconfigjson": |
      {
          "auths": {
              "https://ghcr.io/":{
                  "username":"{% .Secrets.username %}",
                  "password":"{% .Secrets.password %}",
                  "auth":"{% list .Secrets.username ":" .Secrets.password | join "" | b64enc %}"
        	    }
          }
      }     
