name: Build Test And Create
on:
  workflow_call:
    secrets:
      token:
        required: false
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  deploy:
    name: Start Deployment
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - run: |
          gh workflow --repo slaclab/SMCAPTAR_FRONT-Deployment run Deployment -f deployment_image="${{needs.build-docker-images.outputs.IMAGE_TO_DEPLOY}} "
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_WORKFLOW_SECRET }}
