name: Build Test And Create
on:
  workflow_call:
    secrets:
      token:
        required: false
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
    build-docker-images:
      name: Build and Publish Docker Image
      runs-on: ubuntu-latest
      outputs:
        IMAGE_TO_DEPLOY: ${{ steps.meta.outputs.tags }}
      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  deploy:
    name: Start Deployment
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - run: |
          gh workflow --repo slaclab/SMCAPTAR_FRONT-Deployment run Deployment -f deployment_image="${{needs.build-docker-images.outputs.IMAGE_TO_DEPLOY}} "
